[package]
name = "shard"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
starknet.workspace = true
tokio.workspace = true
shard-core.workspace = true
starknet-crypto.workspace = true